# https://giscus.app

[book]
title = "国产编程语言列表"
authors = ["编程爱好者"]
description = "国产编程语言列表"
language = "zh"
multilingual = false
src = "."

[output.html]
git-repository-url = "https://github.com/chai2010/china-programming-languages"
edit-url-template = "https://github.com/chai2010/china-programming-languages/edit/master/{path}"
git-repository-icon = "fa-github"


