# https://giscus.app

[book]
title = "国产编程语言列表"
authors = ["编程爱好者"]
description = "国产编程语言列表"
language = "zh"
multilingual = false
src = "."

[output.html]
additional-css = ["style.css"]
additional-js = ["js/custom.js", "js/bigPicture.js"]
git-repository-url = "https://github.com/china-programming-languages/zh-lang-book"
edit-url-template = "https://github.com/china-programming-languages/zh-lang-book/edit/master/{path}"
git-repository-icon = "fa-github"


